/* tslint:disable */
/* eslint-disable */
/**
 * fwe_backend
 * The API for the Learning Corner project
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: nils.heissner@stud.h-da.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

